permalink: /:month-:day-:year/:title.html
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighting: rouge
highlighter: rouge
exclude: [vendor]
plugins:
  - algoliasearch-jekyll
algolia:
  application_id: 'G160Y1N5OT'
  index_name:     'codeception'  
  read_only_api_key: 'c264188100c4fb7017c4f5702a7d4b8d'
  allowed_extensions:
    - ".markdown"
    - ".html"
  excluded_files:
    - "index.html"
    - "docs-2.0"
    - "docs-1.8"
    - "2012-"
    - "2013-"
    - "2014-"
